nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.4.1.cjs

# Install native optional deps for both Apple Silicon and Rosetta, and Linux for Docker builds
supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux
