apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{ values.component_id }}
  labels:
    app: ${{ values.component_id }}
    app.kubernetes.io/name: ${{ values.component_id }}
automountServiceAccountToken: true
