apiVersion: v2
name: ${{ values.name }}
description: ${{ values.description }}
type: application
version: 0.1.0
appVersion: "latest"

maintainers:
  - name: ${{ values.owner }}

annotations:
  backstage.io/kubernetes-id: ${{ values.name }}
